server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
  servlet:
    session:
      timeout: 1m

spring:
  datasource:
    url: jdbc:mysql://localhost:33060/campus_rental_platform?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: "RrOoOoTt!@#123."
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB

token:
  sign: FF522206-CF91-E2BE-5762-2168F5202870
  time: 60*60*24*7
debug: true

imagePath: "E:\\avatar\\"

#mybatis-plus:
#  global-config:
#    db-config:
#      logic-delete-field: isDelete #默认deleted
#      logic-delete-value: 1
#      logic-not-delete-value: 0


