server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
  servlet:
    session:
      timeout: 1m
spring:
  datasource:
    url: jdbc:mysql://localhost:33060/campus_rental_platform?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: "RrOoOoTt!@#123."

token:
  sign: FF522206-CF91-E2BE-5762-2168F5202870
  time: 60*60*24*7
debug: true

avatarPath: "E:\\avatar\\"
